server:
  port: 8761
spring:
  application:
    name: common_eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    register-with-eureka: false #设置eureka不注册自己
    fetch-registry: false #拉取eureka信息