spring:
  application:
    name: usian-cart-test
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

CART_COOKIE_KEY: CART_COOKIE_KEY
CART_COOKIE_EXPIRE: 604800

